variables:
  COURSIER_CACHE: cache/.coursier

default:
  image: nafg/docker-sbt
  cache:
    key: default
    paths:
      - cache

.sbt_alias: &sbt_alias |-
  shopt -s expand_aliases
  alias sbt='sbt -v -sbt-dir cache/.sbt/launchers -sbt-boot cache/.sbt/boot -ivy cache/.ivy2 -Dslick.testkit-config=test-dbs/testkit-gitlab.conf'

stages:
  - build
  - automerge

build:
  stage: build
  variables:
    POSTGRES_PASSWORD: 1234
    MYSQL_ROOT_PASSWORD: 1234
    CI_DEBUG_TRACE: "true"
  services:
    - postgres:latest
    - mysql

  before_script:
    - *sbt_alias
  script:
    - echo $CI_MERGE_REQUEST_PROJECT_PATH
    - *sbt_alias
    - sbt +test

  artifacts:
    reports:
      junit: "*/target/test-reports/TEST-*.xml"

automerge:
  stage: automerge
  needs: [build]
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH =~ /scala-steward//
  script: curl -X PUT /projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/merge
