variables:
  COURSIER_CACHE: cache/.coursier

default:
  image: nafg/docker-sbt
  cache:
    key: default
    paths:
      - cache


.sbt_alias: &sbt_alias |-
  shopt -s expand_aliases
  alias sbt='sbt -v -sbt-dir cache/.sbt/launchers -sbt-boot cache/.sbt/boot -ivy cache/.ivy2 -Dslick.testkit-config=test-dbs/testkit-gitlab.conf'

build:
  stage: build
  variables:
    POSTGRES_PASSWORD: 1234
    MYSQL_ROOT_PASSWORD: 1234
  services:
    - postgres:latest
    - mysql

  before_script:
    - *sbt_alias
  script:
    - *sbt_alias
    - sbt +test

  artifacts:
    reports:
      junit: "*/target/test-reports/TEST-*.xml"
